/**
 * Mock verification items for demo/fallback mode.
 * Extracted from VerificationQueue to reduce file size.
 */

import type { VerificationItem } from '@/types/verification.types';

export const MOCK_VERIFICATION_ITEMS: VerificationItem[] = [
  {
    id: '1',
    criterionId: '1.1.1',
    criterionName: 'Non-text Content',
    wcagLevel: 'A',
    severity: 'serious',
    confidenceLevel: 'low',
    confidenceScore: 55,
    automatedResult: 'warning',
    automatedNotes: 'Found 3 images with alt text that may need review. Alt text appears to be auto-generated.',
    status: 'pending',
    history: [],
  },
  {
    id: '2',
    criterionId: '1.4.1',
    criterionName: 'Use of Color',
    wcagLevel: 'A',
    severity: 'critical',
    confidenceLevel: 'low',
    confidenceScore: 45,
    automatedResult: 'fail',
    automatedNotes: 'Color-only indicators detected for required form fields. No text or icon alternative provided.',
    status: 'pending',
    history: [],
  },
  {
    id: '3',
    criterionId: '2.1.1',
    criterionName: 'Keyboard',
    wcagLevel: 'A',
    severity: 'critical',
    confidenceLevel: 'manual',
    confidenceScore: 0,
    automatedResult: 'not_tested',
    automatedNotes: 'Custom dropdown component requires manual keyboard testing.',
    status: 'pending',
    history: [],
  },
  {
    id: '4',
    criterionId: '1.2.1',
    criterionName: 'Audio-only and Video-only',
    wcagLevel: 'A',
    severity: 'moderate',
    confidenceLevel: 'manual',
    confidenceScore: 0,
    automatedResult: 'not_tested',
    automatedNotes: 'Media content detected but transcript availability could not be automatically verified.',
    status: 'pending',
    history: [],
  },
  {
    id: '5',
    criterionId: '2.4.4',
    criterionName: 'Link Purpose',
    wcagLevel: 'A',
    severity: 'minor',
    confidenceLevel: 'low',
    confidenceScore: 58,
    automatedResult: 'pass',
    automatedNotes: 'All links have descriptive text. Low confidence due to context-dependent link text.',
    status: 'verified_pass',
    history: [
      {
        id: 'h1',
        status: 'verified_pass',
        method: 'Manual Review',
        notes: 'Reviewed all links - context is clear',
        verifiedBy: 'John Doe',
        verifiedAt: '2024-12-15 10:30',
      },
    ],
  },
  {
    id: '6',
    criterionId: '3.1.1',
    criterionName: 'Language of Page',
    wcagLevel: 'A',
    severity: 'moderate',
    confidenceLevel: 'low',
    confidenceScore: 50,
    automatedResult: 'warning',
    automatedNotes: 'Page language is set but may not match actual content language.',
    status: 'deferred',
    history: [
      {
        id: 'h2',
        status: 'deferred',
        method: 'Manual Review',
        notes: 'Waiting for translation team input',
        verifiedBy: 'Jane Smith',
        verifiedAt: '2024-12-14 15:45',
      },
    ],
  },
];
